# Generated by Django 6.0.6 on 2026-09-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=2024)),
                ('category', models.CharField(default='Tamil Movies', max_length=100)),
                ('language', models.CharField(default='Tamil', max_length=50)),
                ('quality', models.CharField(default='1080p HD', max_length=50)),
                ('poster_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('stream_url', models.CharField(max_length=2000)),
                ('duration', models.CharField(default='2h 30m', max_length=50)),
                ('rating', models.FloatField(default=8.0)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('source_mirror', models.CharField(default='isaimini', max_length=255)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-views_count', 'title'],
            },
        ),
    ]
